//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantManager.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PNHAP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PNHAP()
        {
            this.D_PNHAP = new HashSet<D_PNHAP>();
            this.HOADONMs = new HashSet<HOADONM>();
        }
    
        public int idpnhap { get; set; }
        public Nullable<System.DateTime> ngaynhap { get; set; }
        public string nguoigiao { get; set; }
        public string nguoilapphieu { get; set; }
        public string thukho { get; set; }
        public Nullable<int> idpgiao { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<D_PNHAP> D_PNHAP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADONM> HOADONMs { get; set; }
        public virtual GIAOHANG GIAOHANG { get; set; }
    }
}
