//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantManager.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RestaurantManagerDataEntities : DbContext
    {
        public RestaurantManagerDataEntities()
            : base("name=RestaurantManagerDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CONGTHUC> CONGTHUCs { get; set; }
        public virtual DbSet<D_DONDATDA> D_DONDATDA { get; set; }
        public virtual DbSet<D_GIAOHANG> D_GIAOHANG { get; set; }
        public virtual DbSet<D_PNHAP> D_PNHAP { get; set; }
        public virtual DbSet<D_PYC> D_PYC { get; set; }
        public virtual DbSet<DANHMUC> DANHMUCs { get; set; }
        public virtual DbSet<DONDATDA> DONDATDAs { get; set; }
        public virtual DbSet<DONMH> DONMHs { get; set; }
        public virtual DbSet<HOADONM> HOADONMs { get; set; }
        public virtual DbSet<HOADONTT> HOADONTTs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<MONAN> MONANs { get; set; }
        public virtual DbSet<NCC> NCCs { get; set; }
        public virtual DbSet<NLIEU> NLIEUx { get; set; }
        public virtual DbSet<NLIEU_NCC> NLIEU_NCC { get; set; }
        public virtual DbSet<PNHAP> PNHAPs { get; set; }
        public virtual DbSet<PYC> PYCs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
        public virtual DbSet<D_HOADONTT> D_HOADONTT { get; set; }
        public virtual DbSet<GIAOHANG> GIAOHANGs { get; set; }
        public virtual DbSet<D_DONMH> D_DONMH { get; set; }
        public virtual DbSet<D_HOADONM> D_HOADONM { get; set; }
    }
}
