//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantManager.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarrantyXNKRequestPartMaster
    {
        public string Id { get; set; }
        public string RequestNumber { get; set; }
        public System.DateTime RequestDate { get; set; }
        public System.DateTime RNeedToReceived { get; set; }
        public string RCostCenter { get; set; }
        public string RRequestBy { get; set; }
        public bool RApproval { get; set; }
        public string RApprovalBy { get; set; }
        public Nullable<System.DateTime> RApprovalDate { get; set; }
        public Nullable<bool> RNeedConfirmPrice { get; set; }
        public Nullable<bool> RConfirmPriceApproval { get; set; }
        public string RConfirmPriceBy { get; set; }
        public Nullable<System.DateTime> RConfirmPriceDate { get; set; }
        public Nullable<bool> XNKApproval { get; set; }
        public string XNKApprovalBy { get; set; }
        public Nullable<System.DateTime> XNKApprovalDate { get; set; }
        public string XNKPerformBy { get; set; }
        public Nullable<System.DateTime> XNKPerformDate { get; set; }
        public Nullable<System.DateTime> XNKDateFeedback { get; set; }
        public string XNKFeedbackNote { get; set; }
        public string WMStepKey { get; set; }
        public string WMStepNote { get; set; }
        public string XNKStepKey { get; set; }
        public string XNKStepNote { get; set; }
        public string RequestStatus { get; set; }
        public string Note { get; set; }
        public int Division { get; set; }
        public string SnycBy { get; set; }
        public Nullable<System.DateTime> Snycdate { get; set; }
        public string SysNote { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    }
}
